appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: tVTMw4ozs+vWChH+pD44F5WgFqHwCjSHKUB44NN69V6Ecn+2FEAlYMJ9TJv70yqdTayVN330NNIe4lT9QNanrEo8G70bCDEyThdDwaTCpQ/4cdWd2wvjG7TZeGbYgvHp2ftuqL5TxAecffyPEpL9tykWC86artuSXztDvUeffa9fnOS4tiZXBkINjmV2AaylFO5mYH4rPRoevCwyuQDhOwyAeKq1uZP1ZFSszqBiFf0mgwXnSEzwabEW80l5ln31qwr2DGHcKByIBp23P8d+q7Q9LzNUIwib0UvMnYAbXeqHg6xcdC9FZKjgMiLUgEHUo0r00137qXYMv5wopjD6O5tcgndp+xoEBkJvRTn6A/z7XZrAqDz3b2xWP3pzc1J0UINzQMBT8VuAl8p27w2mWwNjLenYoXmHyF0r4u6D4JW2hUD8aNsBKDAFQQDlrfVCR9ZAsIgGWLGVWV2uCtOKEISGSUtEnEJSI3MhKMUWMKRGox+UmDapMD1kcKHJdkfVrKlx0rklmZJQieTxeUPr/cxtiV31MsVwFg5tRPxD0OVQMnU01s8gWgqYRjqebxU0DUu4tMm4yq4jH19zu9qAngSaIeCsJjpg+nju++M7//PNWuVDya+Eb3Z5PH3lfETWmUEPiXvot25K/bWlIkOMcv2j00UAFSftu2hLT72LXvw=}
bot:
  automerge: true
